# Generated by Django 5.0.1 on 2024-02-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('top_blog', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('author_detail', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/blog/blog_main_img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/blog/blog_2img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/blog/blog_3img')),
                ('paragraph1', models.CharField(max_length=255, null=True)),
                ('paragraph2', models.CharField(max_length=255, null=True)),
                ('paragraph3', models.CharField(max_length=255, null=True)),
                ('paragraph4', models.CharField(max_length=255, null=True)),
                ('paragraph5', models.CharField(max_length=255, null=True)),
                ('paragraph6', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
