# Generated by Django 5.0.1 on 2024-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_portfolio_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_models',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog/author_img'),
        ),
        migrations.AddField(
            model_name='portfolio_models',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/portfolio/author_img'),
        ),
    ]
